spring:
  main.banner-mode: 'OFF'

kafka:
  servers: 127.0.0.1:9092
  appId: com.bastman.codechallenge.watermarkservice.kafkaworker
  sourceTopic: codechallenge.watermarkservice.kafkaworker.publication-received.2017-05-03.001
  sinkTopic: codechallenge.watermarkservice.kafkaworker.watermark-complete.2017-05-03
  sendToSinkEnabled: true

---
spring:
  profiles: dry-run
kafka:
  sendToSinkEnabled: false

